version: '3'
services:
  app:
    build: ./docker/app
    volumes:
    - ./project:/var/www/html:rw
    - ./docker/app/php-fpm.conf:/usr/local/etc/php-fpm.conf
    - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    ports:
        - "8099:80"
